#include "SpecialBS.h"

bool32 HM_BSS_SpecialStage = false;
int32 HM_BSS_SpecialStageID = 0;
bool32 HM_BSS_SuperEmerald = false;

bool32 BSS_Setup_Update_HOOK(bool32 skippedState) {
    RSDK_THIS(BSS_Setup);
    Mod.Super(BSS_Setup->classID, SUPER_UPDATE, NULL);

    // BSS already has the Chaos/Super Emerald target types. Replace the
    // normal medal generated by SetupFinishSequence with the appropriate
    // emerald for the special stage we're running.
    if (HM_BSS_SpecialStage && !globals->specialCleared) {
        for (int32 x = 0; x < BSS_PLAYFIELD_W; ++x) {
            for (int32 y = 0; y < BSS_PLAYFIELD_H; ++y) {
                int32 pos = x * BSS_PLAYFIELD_H + y;
                if (BSS_Setup->playField[pos] == BSS_MEDAL_SILVER || BSS_Setup->playField[pos] == BSS_MEDAL_GOLD)
                    BSS_Setup->playField[pos] = HM_BSS_SuperEmerald ? BSS_EMERALD_SUPER : BSS_EMERALD_CHAOS;
            }
        }
    }

    return false;
}

void HM_BSS_ResetStageState(void) {
    HM_BSS_SpecialStage = false;
    HM_BSS_SpecialStageID = 0;
    HM_BSS_SuperEmerald = false;
}
