#include "SpecialBS.h"

bool32 HM_BSS_SpecialStage = false;
int32 HM_BSS_SpecialStageID = 0;
bool32 HM_BSS_SuperEmerald = false;

static bool32 HM_BSS_ResultPending = false;
static bool32 HM_BSS_ResultSuperEmerald = false;
static int32 HM_BSS_ResultID = 0;
static int32 HM_BSS_ResultRingBonus = 0;
static int32 HM_BSS_ResultPerfectBonus = 0;

static void HM_BSS_StartResultsInUFOScene(void) {
    SaveRAM *saveRAM = GetSaveRAM_Safe();

    // The Special Stage scene already contains SpecialClear in its
    // StageConfig, so its scene-local object ID is valid here.
    for (int32 l = 0; l < LAYER_COUNT; ++l) {
        TileLayer *layer = RSDK.GetTileLayer(l);
        if (layer)
            layer->drawGroup[0] = DRAWGROUP_COUNT;
    }

    // Keep the loaded scene alive only as a host for the result object.
    for (int32 i = 0; i < ENTITY_COUNT; ++i) {
        Entity *entity = RSDK_GET_ENTITY_GEN(i);
        if (entity && entity->classID && entity->classID != UFO_Setup->classID)
            destroyEntity(entity);
    }

    RSDK.ResetEntitySlot(1, SpecialClear->classID, NULL);

    EntitySpecialClear *clear = RSDK_GET_ENTITY(1, SpecialClear);
    if (!clear)
        return;

    clear->isBSS          = true;
    clear->ringBonus     = HM_BSS_ResultRingBonus;
    clear->perfectBonus  = HM_BSS_ResultPerfectBonus;
    clear->machBonus     = 0;
    clear->hasContinues  = false;
    clear->score         = saveRAM->score;
    clear->score1UP      = saveRAM->score1UP;
    clear->lives         = saveRAM->lives;

    if (HM_BSS_ResultSuperEmerald)
        clear->messageType = (HM_globals->currentSave->superEmeralds == 0x7F) ? SC_MSG_ALLEMERALDS : SC_MSG_GOTEMERALD;
    else
        clear->messageType = (saveRAM->chaosEmeralds == 0x7F) ? SC_MSG_ALLEMERALDS : SC_MSG_GOTEMERALD;

    clear->timer    = 512;
    clear->showFade = true;

    HM_BSS_ResultPending = false;
    HM_BSS_ResultID = 0;
}

bool32 BSS_Message_State_LoadPrevScene_HOOK(bool32 skippedState) {
    if (skippedState)
        return true;

    if (!HM_BSS_SpecialStage)
        return false;

    // Failed BSS attempts retain vanilla return behavior. A completed
    // HyperMania BSS stage is turned into an emerald result screen.
    if (!globals->specialCleared)
        return false;

    SaveRAM *saveRAM = GetSaveRAM_Safe();

    HM_BSS_ResultPending = true;
    HM_BSS_ResultSuperEmerald = HM_BSS_SuperEmerald;
    HM_BSS_ResultID = HM_BSS_SpecialStageID;
    HM_BSS_ResultRingBonus = 100 * BSS_Setup->rings;
    HM_BSS_ResultPerfectBonus = BSS_Setup->ringCount ? 0 : 50000;

    if (HM_BSS_SuperEmerald) {
        HM_globals->currentSave->superEmeralds |= 1 << HM_BSS_SpecialStageID;
    }
    else {
        saveRAM->chaosEmeralds |= 1 << HM_BSS_SpecialStageID;
        saveRAM->nextSpecialStage = (saveRAM->nextSpecialStage + 1) % 7;
    }

    SaveGame_SaveGameState();
    HM_Save_SaveFile();

    HM_BSS_ResetStageState();

    // Use the real Special Stage scene solely as a safe host for the
    // already-compiled SpecialClear object. The next state hook immediately
    // converts it into the BSS result screen.
    RSDK.SetScene("Special Stage", "");
    RSDK.LoadScene();
    return true;
}

bool32 UFO_Setup_State_ShowStartMessage_HOOK(bool32 skippedState) {
    if (skippedState)
        return true;

    if (!HM_BSS_ResultPending)
        return false;

    HM_BSS_StartResultsInUFOScene();

    // The UFO setup no longer has a purpose once SpecialClear takes over.
    RSDK_THIS(UFO_Setup);
    destroyEntity(self);
    return true;
}

bool32 BSS_Setup_Update_HOOK(bool32 skippedState) {
    RSDK_THIS(BSS_Setup);
    Mod.Super(BSS_Setup->classID, SUPER_UPDATE, NULL);

    // BSS already has the Chaos/Super Emerald target types. Replace the
    // normal medal generated by SetupFinishSequence with the appropriate
    // emerald for the special stage we're running.
    if (HM_BSS_SpecialStage && !globals->specialCleared) {
        for (int32 x = 0; x < BSS_PLAYFIELD_W; ++x) {
            for (int32 y = 0; y < BSS_PLAYFIELD_H; ++y) {
                int32 pos = x * BSS_PLAYFIELD_H + y;
                if (BSS_Setup->playField[pos] == BSS_MEDAL_SILVER || BSS_Setup->playField[pos] == BSS_MEDAL_GOLD)
                    BSS_Setup->playField[pos] = HM_BSS_SuperEmerald ? BSS_EMERALD_SUPER : BSS_EMERALD_CHAOS;
            }
        }
    }

    return false;
}

void HM_BSS_ResetStageState(void) {
    HM_BSS_SpecialStage = false;
    HM_BSS_SpecialStageID = 0;
    HM_BSS_SuperEmerald = false;
}
